name: tabs
description: A Flutter app made to manage debts with friends.

version: 0.0.1+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  # firebase_auth:
  cloud_firestore:
  provider:
  permission_handler:
  contacts_service:
  flutter_typeahead:
  flutter_money_formatter:
  timeago:
  flutter_spinkit:
  flutter_staggered_animations:

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Prata
      fonts:
        - asset: fonts/Prata-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Light.ttf
          weight: 200
        - asset: fonts/Rubik-Medium.ttf
          weight: 400
